services:
    admin.article:
        class: BlogBundle\Admin\ArticleAdmin
        arguments: [~, BlogBundle\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Blog, group: "article" }

    admin.category:
        class: BlogBundle\Admin\CategoryAdmin
        arguments: [~, BlogBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Blog, group: "category" }
